version: '3'
services:
  mongo:
    env_file:
      test.env
    logging:
      driver: none

  blowltd_payments_server:
    env_file:
      test.env
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "test"]