version: '3'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data
    env_file:
      production.env
    ports:
      - 27017:27017

  blowltd_payments_server:
    build: .
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "start"]
    env_file:
      production.env
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo